name = "mockai"
main = "src/index.ts"
compatibility_date = "2024-10-29"
compatibility_flags = ["nodejs_compat"]

[[unsafe.bindings]]
name = "RATELIMITER"
type = "ratelimit"
namespace_id = "1001"
simple = { limit = 100, period = 60 }

[vars]
MAXIMUM_STREAM_DELAY = 5000
REPO_URL = ""
RATELIMITING_ENABLED = true
ENV = "development"

[env.production]
workers_dev = false

[[env.production.unsafe.bindings]]
name = "RATELIMITER"
type = "ratelimit"
namespace_id = "1001"
simple = { limit = 100, period = 60 }

[env.production.vars]
MAXIMUM_REQUEST_DELAY = 5000
REPO_URL = ""
RATELIMITING_ENABLED = true
ENV = "production"

routes = [
    { pattern = "", custom_domain = "" },
]

